[build-system]
requires = ["flit_core>=3.11,<4", "quart"]
build-backend = "flit_core.buildapi"

[project]
name = "quart-compress2"
version = "1.1.0"
description = "Compress responses in Quart"
readme = "README.md"
requires-python = ">=3.7"
authors = [
    { name = "Florian Dahlitz", email = "f2dahlitz@freenet.de" },
]
classifiers = [
    "License :: OSI Approved :: MIT License",
]
dependencies = [
    "quart",
]

[tool.flit.module]
name = "quart_compress"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py37, py38
[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    pytest
    pytest-asyncio
    Flask-Caching
commands =
    pytest
"""

[tool.black]
line-length = 88
py37 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.tox
  | \.venv
  | build
  | dist
)/
'''